### ISSUE TITLE
[BUG] No XML sitemap found for this site. (cURL error 7)

### ISSUE THREAD

**Issue by bh-teufels** [eliashaeussler/typo3-sitemap-locator#89]
### TYPO3 version

12.4.23

### PHP version

8.3.8

### Extension version

3.3.2

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

macOS 15.0.1

### Current behavior

I have a similar error regarding to https://github.com/eliashaeussler/typo3-warming/issues/137

TYPO3: 12.4.23
warming: 3.3.2
PHP 8.3.8

- Are all languages enabled in your site config? 
=> yes
- Does the appropriate BE user have access to these languages (in case it's not an admin user)? 
=> yes (it is admin user)
- Is your base url properly configured (it must contain a hostname, only / is not enough)? 
=> yes it is https://development.localhost/
- Are your sitemaps accessible (no auth or similar required)? 
=> yes it is without auth available under https://development.localhost/sitemap.xml and working

Debuging SitemapLocator.php > isValidSitemap

-  (string)$sitemap->getUri();
=> https://development.localhost/sitemap.xml
- $this->requestFactory->request((string)$sitemap->getUri(), 'HEAD');
=> Error see below

```
1/1) GuzzleHttp\Exception\ConnectException
cURL error 7: Failed to connect to development.localhost port 443 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://development.localhost/sitemap.xml
```

https://development.localhost/sitemap.xml is reachable see image
![Bildschirmfoto 2024-11-13 um 17 51 05](https://github.com/user-attachments/assets/9d3deead-9861-4f3e-a612-e5b4219aec09)
            

### Expected behavior

Sitemap is configurated correctly and should be found by warming

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @bh-teufels, since the `SitemapLocator` was transferred to EXT:sitemap_locator in the meantime, I transferred your issue as well. Will take a look at it now.

**Comment by bh-teufels** [comment]
still get the error.
is eliashaeussler/typo3-sitemap-locator a requirement of eliashaeussler/typo3-warming?
or do i have to install it independently?

for now i only require eliashaeussler/typo3-warming (installed version 3.3.3)

**Comment by eliashaeussler** [comment]
Yes, `eliashaeussler/typo3-sitemap-locator` is required by `eliashaeussler/typo3-warming`. Since you're running in Composer mode, it should be installed automatically. In order to test the fix, it is necessary to explicitly require `eliashaeussler/typo3-sitemap-locator`, e.g. with `composer require eliashaeussler/typo3-sitemap-locator:dev-fix/sitemap-validation`.

**Comment by bh-teufels** [comment]
Root composer.json requires eliashaeussler/typo3-sitemap-locator dev-fix/sitemap-validation, found eliashaeussler/typo3-sitemap-locator[dev-fix/sitemap-validation] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - eliashaeussler/typo3-warming is locked to version 3.3.3 and an update of this package was not requested.
    - eliashaeussler/typo3-warming 3.3.3 requires eliashaeussler/typo3-sitemap-locator ^0.1.0 -> found eliashaeussler/typo3-sitemap-locator[0.1.0, ..., 0.1.8] but it conflicts with your root composer.json require (dev-fix/sitemap-validation).

**Comment by eliashaeussler** [comment]
Sorry, can you try `composer require "eliashaeussler/typo3-sitemap-locator:dev-fix/sitemap-validation as 0.1.9"`?

**Comment by bh-teufels** [comment]
sitemap_locator dev-fix/sitemap-validation is installed but problem still exist

**Comment by eliashaeussler** [comment]
Out of curiosity: Can you access the XML sitemap with a simple `curl` from your container / machine? In addition, do you have any special configuration in `$GLOBALS['TYPO3_CONF_VARS']['HTTP']`?
