### ISSUE TITLE
[BUG] Constant "EliasHaeussler\Typo3SitemapLocator\Extension::KEY" not defined in Services.yaml

### ISSUE THREAD

**Issue by j-schmidt-magenta-mannheim** [eliashaeussler/typo3-sitemap-locator#9]
### TYPO3 version

12.4.6

### PHP version

8.1.12

### Extension version

0.1.1

### Composer mode

- [ ] I'm running TYPO3 in composer mode.

### Operating system

Windows 10

### Current behavior

Updating EXT:warming installs EXT:sitemap_locator and directly results in the error message
The file "{redacted_some_info_here}/typo3conf/ext/sitemap_locator/Configuration//Services.yaml" does not contain valid YAML: The constant "EliasHaeussler\Typo3SitemapLocator\Extension::KEY" is not defined at line 39 (near "!php/const EliasHaeussler\Typo3SitemapLocator\Extension::KEY").

After replacing that line with       - sitemap_locator we get
Expected to find class "EliasHaeussler\Typo3SitemapLocator\Cache\SitemapsCache" in file "{redacted_shortened_path_here}/typo3conf/ext/sitemap_locator/Classes/Cache/SitemapsCache.php" while importing services from resource "../Classes/*", but it was not found! Check the namespace prefix used with the resource.

We stopped any more attempts to fix this and uninstalled EXT:sitemap_locator for the while being.

### Expected behavior

No errors and blissful sitemap finding.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @j-schmidt-magenta-mannheim, thanks for your issue. Unfortunately, I wasn't able to reproduce it on my end. Can you list all steps you made for me to better try to reproduce the issue?

**Comment by j-schmidt-magenta-mannheim** [comment]
I am sorry, I cannot reproduce it myself any longer. I had hit the update button without clearing all caches before, probably it had something to do with that. Meanwhile all caches have been cleared and the installation went well.

**Comment by eliashaeussler** [comment]
Alright, thanks for your feedback.
